name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgranite-dev libgtk-3-dev libcanberra-dev libayatana-appindicator3-dev libpeas-dev cmake ninja-build valac
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DNO_CONTRIBUTE_DIALOG:BOOL="1" -DUSE_GRANITE:BOOL="1" -DDEFAULT_PLUGINS:STRING="['launcherindicator']" -DBUILD_TESTS:BOOL="1" -G Ninja ..
        ninja
        ninja install
        ./tests/com.github.jmoerman.go-for-it-tests
